CREATE TABLE IF NOT EXISTS `menu` (  `fNo` varchar(5) NOT NULL,  `fName` varchar(10) NOT NULL,  `type` varchar(10) NOT NULL,  `cook` varchar(10) NOT NULL,  PRIMARY KEY (`fNo`)) ENGINE=InnoDB DEFAULT CHARSET=big5;

INSERT INTO `menu` (`fNo`, `fName`, `type`, `cook`) VALUES ('veg01', '高麗菜', '蔬菜', '火鍋'),('veg02', '金針菇', '蔬菜', '火鍋/烤'),('veg03', '青椒', '蔬菜', '烤'),('veg04', '香菇', '蔬菜', '火鍋/烤'),('veg05', '花椰菜', '蔬菜', '烤'),('veg06', '玉米', '蔬菜', '火鍋/烤'),('veg07', '杏鮑菇', '蔬菜', '火鍋/烤'),('veg08', '洋蔥', '蔬菜', '火鍋'),('veg09', '豆皮', '蔬菜', '火鍋'),('veg10', '秀珍菇', '蔬菜', '火鍋/烤'),('veg11', '切片馬鈴薯', '蔬菜', '火鍋'),
 ('sea01', '奶油扇貝', '海鮮', '烤'),('sea02', '草蝦', '海鮮', '烤/火鍋'),('sea03', '花枝', '海鮮', '烤'),('sea04', '大文蛤', '海鮮', '烤/火鍋'),('sea05', '干貝', '海鮮', '烤/火鍋'),('sea06', '秋刀魚', '海鮮', '烤'),('sea07', '椒鹽魚下巴', '海鮮', '烤'),('sea08', '章魚', '海鮮', '烤'),('sea09', '奶油蟹塊', '海鮮', '烤'),('sea10', '柳葉魚', '海鮮', '烤'),('sea11', '魷魚', '海鮮', '烤'),('sea12', '鮑魚角', '海鮮', '烤'),('sea13', '鮭魚肚', '海鮮', '烤'),
('oth01', '甜不辣', '其他', '烤/火鍋'),('oth02', '黑輪', '其他', '烤/火鍋'),('oth03', '貢丸', '其他', '火鍋'),('oth04', '魚丸', '其他', '火鍋'),('oth05', '燕餃', '其他', '火鍋'),('oth06', '魚餃', '其他', '火鍋'),('oth07', '黃金魚蛋', '其他', '火鍋'),('oth08', '嫩豆腐', '其他', '火鍋'),('oth09', '凍豆腐', '其他', '火鍋'),('oth10', '蟹肉棒','其他', '火鍋'),('oth11', '大腸頭', '其他', '烤'),('oth12', '鴨血', '其他', '火鍋'),('oth13', '白飯', '其他', '無'),('oth14', '糯米腸', '其他', '烤'),('oth15', '米血糕', '其他', '烤/火鍋'),('oth16', '魚板', '其他', '火鍋'),
('mea01', '澳洲霜降牛', '肉類', '烤'),('mea02', '嚴選沙朗', '肉類', '烤'),('mea03', '牛五花', '肉類', '烤'),('mea04', '牛小排', '肉類', '烤'),('mea05', '美國雪花牛', '肉類', '烤'),('mea06', '火鍋牛肉片', '肉類', '火鍋'),('mea07', '豬五花', '肉類', '烤'),('mea08', '梅花豬', '肉類', '烤'),('mea09', '松阪豬', '肉類', '烤'),('mea10', '雞肉', '肉類', '烤'),('mea11', '雞翅', '肉類', '烤'),('mea12', '雞腿片', '肉類', '烤'),('mea13', '羊五花', '肉類', '烤'),('mea14', '羊小排', '肉類', '烤'),
('dri01', '可口可樂', '飲料', '汽水'),('dri02', 'Zero可樂', '飲料', '汽水'),('dri03', '雪碧', '飲料', '汽水'),('dri04', '芬達(橘子口味)', '飲料', '汽水'),('dri05', '芬達(葡萄口味)', '飲料', '汽水'),('dri06', '可爾必思', '飲料', '汽水'),('dri07', '加鹽沙士', '飲料', '汽水'),('dri08', '雀巢雪梨茶', '飲料', '茶類'),('dri09', '雀巢檸檬茶', '飲料', '茶類'),('dri10', '泰式撞奶', '飲料', '茶類'),('dri11', '冬瓜茶', '飲料', '茶類'),
('des01', '日式麻糬', '甜點', '甜點'),('des02', '棉果子', '甜點', '甜點'),('des03', '布朗尼巧克力', '甜點', '甜點'),('des04', '手作銅鑼燒', '甜點', '甜點'),('des05', '義式起士條', '甜點', '副餐'),('des06', '冰心地瓜', '甜點', '副餐'),('des07', '特濃奶同香腸', '甜點', '副餐'),('des08', '黃金子持燒', '甜點', '副餐');

CREATE TABLE IF NOT EXISTS `info` (  `cNo` int(10) NOT NULL AUTO_INCREMENT,  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ,  `tNo` varchar(5) NOT NULL,  PRIMARY KEY (`cNo`)) ENGINE=InnoDB  DEFAULT CHARSET=big5 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `order` (  `oNo` int(10) NOT NULL AUTO_INCREMENT,  `cNo` int(10) NOT NULL, `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ,  `fName` varchar(10) NOT NULL,  `fa` int(1) NOT NULL,`done` boolean NOT NULL,PRIMARY KEY(`oNo`)) ENGINE=InnoDB DEFAULT CHARSET=big5 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `satisfaction` (  `cNo` int(10) NOT NULL,  `first` varchar(2) NOT NULL,`info` varchar(10) NOT NULL,`what` varchar(10) NOT NULL,   `sMeat` int(1) NOT NULL,  `sSeafood` int(1) NOT NULL,  `sVege` int(1) NOT NULL,  `sDessert` int(1) NOT NULL,  `sDrink` int(1) NOT NULL,  `sOther` int(1) NOT NULL,`sService` int(1) NOT NULL,  `comments` varchar(100) NOT NULL,PRIMARY KEY(`cNo`)) ENGINE=InnoDB DEFAULT CHARSET=big5;